-- DEPRECATED — moved to backend/migrations/conversations.sql, which also
-- fixes the RLS policy below (this version's `using (true)` with no `to`
-- clause grants full access to the anon key, not just the backend).
-- Kept only so any environment that already ran this file's CREATE TABLE
-- isn't left without a record of it; do not run this file on a fresh
-- database — use backend/migrations/conversations.sql instead.
